name: native_shared_preferences
description: This packages is a copy of the shared_prefrences package but without the prefix in the keys. Is used to migrate the data from previous native app.
version: 1.0.5
homepage: https://github.com/yeniel/native_shared_preferences

environment:
  sdk: '>=2.12.0 <2.20.0'
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: yeniellandestoy.native_shared_preferences
        pluginClass: NativeSharedPreferencesPlugin
      ios:
        pluginClass: NativeSharedPreferencesPlugin

